"""Non-interactive install runner for the IDE.

Wraps the core install.py logic (pip install + file copy + config write)
so the IDE settings page can trigger a real installation without interactive prompts.
"""

from __future__ import annotations

import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Callable

from shared.paths import get_repo_root

from .models import InstallationActionResult, InstallationCheck


def _find_requirements(repo_root: Path) -> Path | None:
    candidates = [repo_root / "requirements.txt"]
    for path in candidates:
        if path.exists():
            return path
    return None


def _pip_install_streaming(
    python_executable: str,
    requirements_path: str,
    on_output: Callable[[str], None] | None = None,
) -> tuple[bool, str]:
    """Run pip install -r with streaming output. Returns (success, combined_output)."""
    try:
        process = subprocess.Popen(
            [python_executable, "-m", "pip", "install", "-r", requirements_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        lines: list[str] = []
        if process.stdout:
            for line in process.stdout:
                stripped = line.rstrip()
                lines.append(stripped)
                if on_output:
                    on_output(stripped)

        returncode = process.wait(timeout=300)
        combined = "\n".join(lines)
        if returncode != 0:
            return False, combined or f"pip install failed with exit code {returncode}"
        return True, combined
    except subprocess.TimeoutExpired:
        process.kill()
        return False, "pip install timed out (300s)"
    except (OSError, subprocess.SubprocessError) as exc:
        return False, str(exc)


def _copy_plugin_files(repo_root: Path, plugins_dir: Path) -> tuple[bool, str]:
    """Copy ida_mcp.py and ida_mcp/ from repo root to the target plugins dir."""
    source_plugin_file = repo_root / "ida_mcp.py"
    source_plugin_dir = repo_root / "ida_mcp"

    if not source_plugin_file.exists():
        return False, f"ida_mcp.py not found at {source_plugin_file}"
    if not source_plugin_dir.exists():
        return False, f"ida_mcp/ directory not found at {source_plugin_dir}"

    try:
        plugins_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_plugin_file, plugins_dir / source_plugin_file.name)
        shutil.copytree(
            source_plugin_dir,
            plugins_dir / source_plugin_dir.name,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns(
                "__pycache__", "*.pyc", "*.pyo", ".pytest_cache"
            ),
        )
        return True, ""
    except OSError as exc:
        return False, str(exc)


def _quote_config_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value).replace('"', '\\"')
    return f'"{text}"'


def _render_config(config: dict[str, Any]) -> str:
    return "\n".join(
        [
            "# IDA-MCP configuration file",
            f"# Generated by IDE installer on {datetime.now().isoformat(timespec='seconds')}",
            "",
            "# Transport switches",
            f"enable_stdio = {_quote_config_value(config.get('enable_stdio', False))}",
            f"enable_http = {_quote_config_value(config.get('enable_http', True))}",
            f"enable_unsafe = {_quote_config_value(config.get('enable_unsafe', True))}",
            f"wsl_path_bridge = {_quote_config_value(config.get('wsl_path_bridge', False))}",
            "",
            "# HTTP gateway settings",
            f"http_host = {_quote_config_value(config.get('http_host', '127.0.0.1'))}",
            f"http_port = {_quote_config_value(config.get('http_port', 11338))}",
            f"http_path = {_quote_config_value(config.get('http_path', '/mcp'))}",
            "",
            "# IDA instance settings",
            f"ida_default_port = {_quote_config_value(config.get('ida_default_port', 10000))}",
            f"ida_host = {_quote_config_value(config.get('ida_host', '127.0.0.1'))}",
            f"ida_path = {_quote_config_value(config.get('ida_path', ''))}",
            f"ida_python = {_quote_config_value(config.get('ida_python', ''))}",
            f"open_in_ida_bundle_dir = {_quote_config_value(config.get('open_in_ida_bundle_dir', ''))}",
            f"open_in_ida_autonomous = {_quote_config_value(config.get('open_in_ida_autonomous', True))}",
            f"auto_start = {_quote_config_value(config.get('auto_start', False))}",
            f"server_name = {_quote_config_value(config.get('server_name', 'IDA-MCP'))}",
            "",
            "# General settings",
            f"request_timeout = {_quote_config_value(config.get('request_timeout', 30))}",
            f"debug = {_quote_config_value(config.get('debug', False))}",
            "",
        ]
    )


def _write_config(
    config: dict[str, Any], plugins_dir: Path
) -> tuple[bool, str, str | None]:
    """Write config.conf to plugins_dir/ida_mcp/config.conf."""
    config_dir = plugins_dir / "ida_mcp"
    config_path = config_dir / "config.conf"
    try:
        config_dir.mkdir(parents=True, exist_ok=True)
        config_path.write_text(_render_config(config), encoding="utf-8")
        return True, "", str(config_path)
    except OSError as exc:
        return False, str(exc), None


def run_install(
    python_executable: str,
    ida_path: str | None,
    plugin_dir: str | None,
    ida_mcp_config_dict: dict[str, Any] | None,
    *,
    on_progress: Callable[[str], None] | None = None,
) -> InstallationActionResult:
    """Run the full non-interactive installation pipeline.

    Args:
        python_executable: Path to the Python interpreter.
        ida_path: Path to the IDA executable (used to derive plugin_dir).
        plugin_dir: Target plugins directory.
        ida_mcp_config_dict: Config values to write into config.conf.
        on_progress: Optional callback invoked with progress messages in real-time.
    """
    repo_root = get_repo_root()
    warnings: list[str] = []

    def _log(msg: str) -> None:
        if on_progress:
            on_progress(msg)

    # --- Validate inputs ---
    python_path = Path(python_executable) if python_executable else None
    if not python_path or not python_path.exists():
        _log("[ERROR] Python executable does not exist")
        return InstallationActionResult(
            action="install",
            ok=False,
            summary="python executable does not exist",
            check=InstallationCheck(
                plugin_dir=None,
                plugin_dir_exists=False,
                config_path=None,
                config_exists=False,
                python_executable=python_executable,
                python_exists=bool(python_path and python_path.exists()),
                ida_mcp_py_exists=False,
                ida_mcp_package_exists=False,
                summary="python executable does not exist",
                warnings=["python executable does not exist"],
            ),
            warnings=["python executable does not exist"],
        )

    if plugin_dir:
        plugins_dir = Path(plugin_dir)
    elif ida_path:
        plugins_dir = Path(ida_path).parent / "plugins"
    else:
        _log("[ERROR] No plugin directory configured")
        return InstallationActionResult(
            action="install",
            ok=False,
            summary="no plugin_dir or ida_path provided",
            check=InstallationCheck(
                plugin_dir=None,
                plugin_dir_exists=False,
                config_path=None,
                config_exists=False,
                python_executable=python_executable,
                python_exists=True,
                ida_mcp_py_exists=False,
                ida_mcp_package_exists=False,
                summary="missing plugin_dir",
                warnings=["plugin_dir not provided"],
            ),
            warnings=["plugin_dir not provided"],
        )

    # --- Step 1: pip install ---
    total_steps = 3
    requirements_path = _find_requirements(repo_root)
    pip_ok = True
    pip_output = ""
    _log(f"[1/{total_steps}] Installing Python dependencies...")
    if requirements_path:
        _log(f"  Python: {python_executable}")
        _log(f"  Requirements: {requirements_path}")
        pip_ok, pip_output = _pip_install_streaming(
            str(python_path),
            str(requirements_path),
            on_output=lambda line: _log(f"  {line}"),
        )
        if not pip_ok:
            warnings.append(f"pip install failed: {pip_output}")
            _log(f"[1/{total_steps}] FAILED — pip install failed")
        else:
            _log(f"[1/{total_steps}] Dependencies installed successfully")
    else:
        warnings.append("requirements.txt not found in repo root")
        pip_ok = False
        _log("[1/3] FAILED — requirements.txt not found")

    # --- Step 2: Copy plugin files ---
    _log(f"[2/{total_steps}] Copying plugin files...")
    _log(f"  Source: {repo_root}")
    _log(f"  Target: {plugins_dir}")
    copy_ok, copy_error = _copy_plugin_files(repo_root, plugins_dir)
    if not copy_ok:
        warnings.append(f"file copy failed: {copy_error}")
        _log(f"[2/{total_steps}] FAILED — {copy_error}")
    else:
        _log(f"  Copied ida_mcp.py")
        _log(f"  Copied ida_mcp/")
        _log(f"[2/{total_steps}] Plugin files copied successfully")

    # --- Step 3: Write config ---
    _log(f"[3/{total_steps}] Writing configuration...")
    write_ok = True
    write_error = ""
    config_path_str: str | None = None
    config_dict = dict(ida_mcp_config_dict or {})
    if ida_path and not config_dict.get("ida_path"):
        config_dict["ida_path"] = ida_path
    if config_dict:
        write_ok, write_error, config_path_str = _write_config(config_dict, plugins_dir)
        if not write_ok:
            warnings.append(f"config write failed: {write_error}")
            _log(f"[3/{total_steps}] FAILED — {write_error}")
        else:
            _log(f"  Config: {config_path_str}")
            _log(f"[3/{total_steps}] Configuration written successfully")

    # --- Summary ---
    overall_ok = pip_ok and copy_ok and write_ok
    if overall_ok:
        summary = "Installation completed successfully"
        _log("")
        _log("✓ Installation completed successfully")
    else:
        parts = []
        if not pip_ok:
            parts.append("pip install incomplete")
        if not copy_ok:
            parts.append("file copy failed")
        if not write_ok:
            parts.append("config write failed")
        summary = "; ".join(parts)
        _log("")
        _log(f"✗ Installation incomplete: {summary}")

    ida_mcp_py_exists = (plugins_dir / "ida_mcp.py").exists()
    ida_mcp_package_exists = (plugins_dir / "ida_mcp").exists()
    config_exists = (
        (plugins_dir / "ida_mcp" / "config.conf").exists() if config_path_str else False
    )

    check = InstallationCheck(
        plugin_dir=str(plugins_dir),
        plugin_dir_exists=plugins_dir.exists(),
        config_path=config_path_str,
        config_exists=config_exists,
        python_executable=str(python_path),
        python_exists=True,
        ida_mcp_py_exists=ida_mcp_py_exists,
        ida_mcp_package_exists=ida_mcp_package_exists,
        requirements_path=str(requirements_path) if requirements_path else None,
        summary=summary,
        warnings=warnings,
    )

    return InstallationActionResult(
        action="install",
        ok=overall_ok,
        summary=summary,
        check=check,
        config_path=config_path_str,
        created=config_exists,
        already_exists=False,
        warnings=warnings,
    )
